

NODE_HOST = "127.0.0.1"
NODE_PORTS = [8888, 8889, 8890]
REPLICATION_FACTOR = 2  

     
HEARTBEAT_INTERVAL = 2             
HEARTBEAT_TIMEOUT = 5  
NODE_TIMEOUT = 15 

STATUS_OK = "OK"
STATUS_ERROR = "ERROR"
STATUS_NOT_FOUND = "NOT_FOUND"


