import hashlib
# config.py

NODE_HOST = "127.0.0.1"
NODE_PORTS = [8888, 8889, 8890]
REPLICATION_FACTOR = 2  


BUFFER_SIZE = 4096      
ENCODING = 'utf-8'      
HEARTBEAT_INTERVAL = 5  
NODE_TIMEOUT = 15 

CMD_PUT = "PUT"
CMD_GET = "GET"
CMD_DELETE = "DELETE"
CMD_HEARTBEAT = "HEARTBEAT"
CMD_SYNC = "SYNC"
CMD_JOIN = "JOIN"

STATUS_OK = "OK"
STATUS_ERROR = "ERROR"
STATUS_NOT_FOUND = "NOT_FOUND"
STATUS_REDIRECT = "REDIRECT"
